### ISSUE TITLE
Change config files

### ISSUE THREAD

**Issue by mecjack** [Cocolabs-SAS/cocorico-docker#1]
I had to change the following in folder supervisord.d:

stdout_logfile = tmp/cocorico.log
to
stdout_logfile = /tmp/cocorico.log

stdout_logfile = tmp/mongo.log
to
stdout_logfile = /tmp/mongo.log

stdout_logfile = tmp/mysql.log
to
stdout_logfile = /tmp/mysql.log

**Comment by giorgio654** [comment]
Hello @mecjack,
Thanks for your feedback, a new release is coming this afternoon.

**Comment by giorgio654** [comment]
https://hub.docker.com/r/cocolabs/cocorico/
:+1:
