### ISSUE TITLE
Docker built from the code base does not launch successfully

### ISSUE THREAD

**Issue by ht512512** [Cocolabs-SAS/cocorico-docker#10]
Platform = Ubuntu 18.04
1. Cloned the git repo
2. Did "Docker build" to build the container successfully
3. Did "Docker run" as describe in the the Readme.md here (uses mysql and mongodb in the container). Failed. It tried the Cocorico script 5 times with error exit; after which it gave up. The logtail showed the error of mysql "Connection refused"
4. I changed the parameter to point to mysql on another server I have and rebuilt the container. Of course, created cocorico db and user on the mysql server.
5. Ran the new container. This time mysql connection was established without any error and container seemed to have launched without any errors.
6. Tried to access the app at http://localhost/en and got an exception because of a bad query. I have included the exception below. BTW, looking at the mysql server, all the tables were created properly.

Any help about how to proceed in making my local container work will be very valuable. I rather use docker than do a host installation. Thank you.

Hemant

======== Exception =================
An exception occurred while executing 'SELECT DISTINCT id_1 FROM (SELECT '' AS sclr_0, l0_.id AS id_1, l0_.price AS price_2, l0_.certified AS certified_3, l0_.average_rating AS average_rating_4, l0_.createdAt AS createdAt_5, l1_.title AS title_6, l1_.description AS description_7, l1_.slug AS slug_8, l1_.locale AS locale_9, l1_.id AS id_10, l2_.id AS id_11, l3_.id AS id_12, l3_.lft AS lft_13, l3_.lvl AS lvl_14, l3_.rgt AS rgt_15, l3_.root AS root_16, l4_.name AS name_17, l4_.locale AS locale_18, l4_.id AS id_19, l5_.id AS id_20, l5_.name AS name_21, u6_.id AS id_22, u6_.first_name AS first_name_23, u7_.id AS id_24, u7_.name AS name_25, l8_.id AS id_26, l8_.country AS country_27, l8_.city AS city_28, l8_.route AS route_29, g9_.id AS id_30, g9_.lat AS lat_31, g9_.lng AS lng_32, l4_.locale AS locale_33, u7_.position AS position_34, l1_.locale AS locale_35, l0_.status AS status_36, l0_.createdAt AS createdAt_37 FROM listing l0_ LEFT JOIN listing_translation l1_ ON l0_.id = l1_.translatable_id LEFT JOIN listing_listing_category l2_ ON l0_.id = l2_.listing_id LEFT JOIN listing_category l3_ ON l2_.listing_category_id = l3_.id LEFT JOIN listing_category_translation l4_ ON l3_.id = l4_.translatable_id AND (l4_.locale = ?) LEFT JOIN listing_image l5_ ON l0_.id = l5_.listing_id LEFT JOIN `user` u6_ ON l0_.user_id = u6_.id LEFT JOIN user_image u7_ ON u6_.id = u7_.user_id AND (u7_.position = 1) LEFT JOIN listing_location l8_ ON l0_.location_id = l8_.id LEFT JOIN geo_coordinate g9_ ON l8_.coordinate_id = g9_.id WHERE l1_.locale = ? AND l0_.status = ? ORDER BY l5_.position asc, u7_.position asc) dctrn_result ORDER BY createdAt_5 DESC LIMIT 6' with params ["en", "en", 2]:

SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'dctrn_result.createdAt_5' which is not in SELECT list; this is incompatible with DISTINCT

**Comment by giorgio654** [comment]
Hello @ht512512,

If you want to build your own image, launch the docker run in an empty directory or use this command :
```docker run --name cocorico -ti -p 80:8000 -p 3306:3306 -p 9001:9001 -p 27017:27017  -v `pwd`/cocorico:/cocorico -v `pwd`/cocorico/tmp/mysql:/var/lib/mysql -v `pwd`/cocorico/tmp/mongo:/data/db -e HOST_UID=$UID [image_id]```

Then cocorico source code will be initialized as usual.
