### ISSUE TITLE
While starting/deploying Docker container I received this error

### ISSUE THREAD

**Issue by hoodpablo** [Cocolabs-SAS/cocorico-docker#12]
While starting/deploying Docker container I received this error, any clues?
Mthks

`22:27:28 [file+] /cocorico/app/../web/js/compiled/all_date-time_15.js
22:27:28 [file+] /cocorico/app/../web/js/compiled/all_cookie-consent_16.js

  There are no commands defined in the "server" namespace.

mysqld is alive
sh: (user): unknown operand

  There are no commands defined in the "server" namespace.

mysqld is alive
sh: (user): unknown operand

  There are no commands defined in the "server" namespace.

mysqld is alive
sh: (user): unknown operand

  There are no commands defined in the "server" namespace.

mysqld is alive
sh: (user): unknown operand

  There are no commands defined in the "server" namespace.
`

**Comment by chetanppatil** [comment]
Yes,
I am also getting same error

**Comment by latcher1** [comment]
Same problem here

**Comment by hoodpablo** [comment]
hello @giorgio654 any clues about this? many thanks in advance.

**Comment by giorgio654** [comment]
Hello @hoodpablo @Chetan07j @latcher1  ,

The built-in Web server is no longer available in Cocorico.
An update is coming very soon including nginx and php-fpm.
