### ISSUE TITLE
Broken Page

### ISSUE THREAD

**Issue by latcher1** [Cocolabs-SAS/cocorico-docker#16]
I installed Cocorico with Docker (the newest version) but i got a broken page. There is only HTML on my page.  -> http://13.81.68.138/en/

How can i change it?

**Comment by dazrour** [comment]
Hi @latcher1
You need to modify app/config/parameters.yml and add your url to cocorico.assets_base_urls.
Hope that helps.

**Comment by giorgio654** [comment]
Hello @latcher1 @dazrour,
In fact, the parameter should be in your case:
`cocorico.assets_base_urls: 'http://13.81.68.138'`
