### ISSUE TITLE
Mysql connection error

### ISSUE THREAD

**Issue by vichanse** [Cocolabs-SAS/cocorico-docker#18]
Hello +1 for @wasbhs issue.
I'm running docker on Mac too. And i'm having the same error

> SQLSTATE[HY000] [2002] No such file or directory

Thank you for your support and gr8 job

**Comment by giorgio654** [comment]
Hello @vichanse @wasbhs,
Currently the docker image is only supported on Linux OS. https://github.com/Cocolabs-SAS/cocorico-docker/blame/master/README.md#L17

**Comment by mysticaltech** [comment]
@giorgio654 I see, I'm having the same error on macOS... I really don't get it, the docker system is supposed to make it easy to abstract the OS layer away no? The docker base image is Alpine and MySQL + MongoDB are self-contained no? Why this error? It really does not make sense to me!

**Comment by Crocodeal** [comment]
<img width="855" alt="Capture d’écran 2019-11-14 à 23 29 15" src="https://user-images.githubusercontent.com/36205441/68904946-a9b88e00-073f-11ea-85e1-478a3d6e6dcb.png">

No fixed again ? Its works on Linux but need to be on mac to create hybrid app so 

Im on Mac too and i have it : 
(3/3) ConnectionExceptionAn exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory
--
in AbstractMySQLDriver.php line 108
at AbstractMySQLDriver->convertException('An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory', object(PDOException))in DBALException.php line 176
at DBALException::wrapException(object(Driver), object(PDOException), 'An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory')in DBALException.php line 161
at DBALException::driverException(object(Driver), object(PDOException))in Driver.php line 47
at Driver->connect(array('driver' => 'pdo_mysql', 'host' => 'localhost', 'port' => null, 'dbname' => 'cocorico', 'user' => 'cocorico', 'password' => 'cocorico', 'charset' => 'UTF8'), 'cocorico', 'cocorico', array())in Connection.php line 372
at Connection->connect()in ContainerBuilder.php line 79
at ContainerBuilder->connect()in ContainerBuilder.php line 51
at ContainerBuilder->compile()in Kernel.php line 637
at Kernel->initializeContainer()in Kernel.php line 135
at Kernel->boot()in Kernel.php line 195
at Kernel->handle(object(Request))in app_dev.php line 28
