### ISSUE TITLE
wrong adress

### ISSUE THREAD

**Issue by alcommit** [Cocolabs-SAS/cocorico-docker#2]
Hi,
Thanx you for this new release, but I got an issue as of:
latest: Pulling from cocolabs/cocorico
1eae7a7426b0: Pull complete 
77bcf2a3893d: Pull complete 
3485ecf0d645: Pull complete 
91cf0adafd9a: Pull complete 
Digest: sha256:4f535f4a373783cc820572aa97c064b51f524ca510d87db557381ac866cd3175
Status: Downloaded newer image for cocolabs/cocorico:latest
docker: Error response from daemon: driver failed programming external connectivity on endpoint cocorico (2bdfc3ccc63c0630526e1432f51066db95c1afdb8579498787bb9633cb899f1e): Error starting userland proxy: listen tcp 0.0.0.0:80: listen: address already in use.
The wrong adress is in your code or  do I set it?
THX

**Comment by giorgio654** [comment]
Hello @alcommit,

Thanks for the feedback, you can use another port like 8000 for example:
``` bash
docker run --name cocorico -ti -p 8000:8000 -p 3306:3306 -p 9001:9001 -p 27017:27017  -v `pwd`:/cocorico -v `pwd`/tmp/mysql:/var/lib/mysql -v `pwd`/tmp/mongo:/data/db -e HOST_UID=$UID cocolabs/cocorico
```
Then your Cocorico address would be: [http://localhost:8000/](http://localhost:8000/)
