### ISSUE TITLE
problem with cocoricodocker_php-cli_1 container

### ISSUE THREAD

**Issue by frankyadam** [Cocolabs-SAS/cocorico-docker#2]
Hello, 

When I want to start the container with kinematic, it stops and says 

container_linux.go:265: starting container process caused "process_linux.go:368: container init caused \"rootfs_linux.go:57: mounting \\\"/private/tmp/com.apple.launchd.bjVgveh5Hc/Listeners\\\" to rootfs \\\"/var/lib/docker/overlay2/97a0d572f5b05ca0d9e339d308bb660b559b19d0e69be70421a8be38f0bc59ea/merged\\\" at \\\"/var/lib/docker/overlay2/97a0d572f5b05ca0d9e339d308bb660b559b19d0e69be70421a8be38f0bc59ea/merged/ssh-agent\\\" caused \\\"not a directory\\\"\""

Anyone has an idea of what went wrong ??

I'm newbie and quite lost ;-)

Thanks for the help !

Have a good day

**Comment by Bl3izingard** [comment]
Try to reinstall with this solution 

https://github.com/Cocolabs-SAS/cocorico-docker/issues/5

**Comment by giorgio654** [comment]
Hi @frankyadam ,
Sorry, MacOSX system isn't yet supported. You can use only Linux or Windows with this docker composition for now.
