### ISSUE TITLE
`Could not open input file: app/console` error running docker image

### ISSUE THREAD

**Issue by sudotestuser** [Cocolabs-SAS/cocorico-docker#21]
Hi there,

On a clean Ubuntu 18.10 install, with Docker version 18.06.1-ce, running 

``docker run --name cocorico -ti -p 80:80 -p 3306:3306 -p 9001:9001 -p 27017:27017  -v `pwd`:/cocorico -v `pwd`/tmp/mysql:/var/lib/mysql -v `pwd`/tmp/mongo:/data/db -e HOST_UID=$UID cocolabs/cocorico`` 

results for me in:

`Could not open input file: app/console`
`Could not open input file: app/console`
`Could not open input file: app/console`
`cocorico is alive`

[http://localhost:9001](http://localhost:9001):
![cocorico-sup](https://user-images.githubusercontent.com/53816/54524394-83f1a400-497a-11e9-8071-de32eb1b6b0e.png)

[http://localhost/en/](http://localhost/en/):
> Symfony 3.4.1 HTTP 500 Internal Server Error
> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cocorico.listing' doesn't exist

Any suggestions how to resolve my issue? Thanks!

**Comment by giorgio654** [comment]
Hello @sudotestuser ,
You can pull the new cocorico image to avoid this issue.
