### ISSUE TITLE
Mysql is not working

### ISSUE THREAD

**Issue by Damiano1376** [Cocolabs-SAS/cocorico-docker#23]
Hello,
I am facing this issue with the contener : Can't open and lock privilege tables: Table 'mysql.user' doesn't exist
ERROR: 1146  Table 'mysql.user' doesn't exist

Does anyone knows how to fix it ?

**Comment by giorgio654** [comment]
Hello @Damiano1376 ,
You can pull the new cocorico image to avoid this issue.
