### ISSUE TITLE
Crash docker install

### ISSUE THREAD

**Issue by mrexojo** [Cocolabs-SAS/cocorico-docker#24]
Crash when docker install about SQL driver
`Generating autoload files
> ComponentInstaller\Installer::postAutoloadDump
Compiling component files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

In AbstractMySQLDriver.php line 108:

  An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or dir
  ectory

In PDOConnection.php line 47:

  SQLSTATE[HY000] [2002] No such file or directory

In PDOConnection.php line 43:

  SQLSTATE[HY000] [2002] No such file or directory

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the symfony-scripts event terminated with an exception

  [RuntimeException]
  An error occurred when executing the "'cache:clear --no-warmup'" command:

  In AbstractMySQLDriver.php line 108:

    An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or dir
    ectory

  In PDOConnection.php line 47:

    SQLSTATE[HY000] [2002] No such file or directory

  In PDOConnection.php line 43:

    SQLSTATE[HY000] [2002] No such file or directory

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...
`

**Comment by Saraivahost** [comment]
Hello!
I have the same problem.

**Comment by mosidze** [comment]
same for me

**Comment by giorgio654** [comment]
Hello @mrexojo @Saraivahost @mosidze ,
You can pull the new cocorico image to avoid this issue.

**Comment by robertoamoreno** [comment]
This is still not fixed in the latest version
