### ISSUE TITLE
Cocorico File Not found

### ISSUE THREAD

**Issue by bindmisson** [Cocolabs-SAS/cocorico-docker#25]
Hello I have deployed latest cocorico image and it's showing File Not found error in frontend.

Please give a fix.

**Comment by bindmisson** [comment]
"/cocorico/web/" failed (13: Permission denied), client: 172.17.0.1, server: , request: "GET / HTTP/1.1", host: "127.0.0.1:8080"

**Comment by bindmisson** [comment]
I have fixed the issue.

Now, It installed but GUI not looks good.


![Screenshot from 2019-04-26 05-14-01](https://user-images.githubusercontent.com/7593069/56774919-44707000-67e2-11e9-892c-4d61160251e9.png)

**Comment by hosam4her** [comment]
I have same issue, after clean install of Cocorico docker image, I get ( File not found) Error.
How to solve this?

also, I noticed in (Supervisor) that Bootstrap is not running, and refuse to run.
![image](https://user-images.githubusercontent.com/45920807/57609467-3d31bc00-756f-11e9-8516-dc0d0cb91f31.png)

**Comment by hosam4her** [comment]
2019-05-13 10:02:53,754 INFO exited: bootstrap (exit status 0; not expected)

2019-05-13 10:02:54,870 ERRO 197.161.72.250:57626 - - [13/May/2019:10:02:54 +0000] "GET /?message=ERROR%3A%20Process%20bootstrap%3A%20spawn%20error HTTP/1.1" 200 6265

**Comment by SilvioGiancola** [comment]
Hi,
I have a similar error, have you found a fix?

I am running it on my workstation (Ubuntu 16.04) and the terminal show the following warnings:
```
giancos@PC-KW-60110:~/git/cocorico-docker$ sudo docker run --name cocorico -ti -p 80:80 -p 3306:3306 -p 9001:9001 -p 27017:27017  -v `pwd`:/cocorico -v `pwd`/tmp/mysql:/var/lib/mysql -v `pwd`/tmp/mongo:/data/db -e HOST_UID=$UID cocolabs/cocorico
Unable to find image 'cocolabs/cocorico:latest' locally
latest: Pulling from cocolabs/cocorico
c87736221ed0: Pull complete 
c4510e94c06d: Pull complete 
261ce2f932b8: Pull complete 
422711fe38cd: Pull complete 
Digest: sha256:d06978f5684eba820ca9d20277bc0779ea5a854c57be67f61a96cfd90488ec15
Status: Downloaded newer image for cocolabs/cocorico:latest
PHP Warning:  Version warning: Imagick was compiled against Image Magick version 1799 but version 1800 is loaded. Imagick will run but may behave surprisingly in Unknown on line 0
Composer could not find a composer.json file in /cocorico
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
PHP Warning:  Version warning: Imagick was compiled against Image Magick version 1799 but version 1800 is loaded. Imagick will run but may behave surprisingly in Unknown on line 0
Could not open input file: bin/console
PHP Warning:  Version warning: Imagick was compiled against Image Magick version 1799 but version 1800 is loaded. Imagick will run but may behave surprisingly in Unknown on line 0
Could not open input file: bin/console
PHP Warning:  Version warning: Imagick was compiled against Image Magick version 1799 but version 1800 is loaded. Imagick will run but may behave surprisingly in Unknown on line 0
Could not open input file: bin/console
cocorico is alive
```

Same here, the Supervisor is working, but bootstrap is in "exited" state.

![image](https://user-images.githubusercontent.com/7395008/58151596-c7b2a380-7c72-11e9-9936-c7f1c9a77ff3.png)

Thanks for letting me know if you find a fix.

Cheers

**Comment by giorgio654** [comment]
Hello @hosam4her @bindmisson @SilvioGiancola ,
Please make sure that the parameter "cocorico_core.assets_base_urls:" is set properly in your Symfony env parameters "app/config/parameters.yml" and reload your cache.

**Comment by americandy** [comment]
Hello,

did you solve it with the editing of the paramters.yml ?

Unfortunally i have the same issue. I have a little Space at DigitalOcean with Docker.
I edit the parameters.yml file and copied in the container.

But i get now "File not Found".

I set the cocorico_core.assets_base_ulrs to the Server IP, so it looks like:
cocorico_core.assets_base_urls: 'http://134.209.249.25'

Tried also with :80 and :8080 but also doesnt work.

Oh and for sure i cleared the Cache after that in the Container with:
php bin/console cache:clear --no-warmup --env=prod

Anyone have an idea what else i could change?

Thanks

best Regards

**Comment by bindmisson** [comment]
Hello,

We have found the fix .

https://vishnulal.tech

https://spotfixcrew.com

**Comment by sufyanaslam** [comment]
@bindmisson can you please post the fix here?

**Comment by americandy** [comment]
@sufyanaslam do you have the same error?

**Comment by sufyanaslam** [comment]
@americandy I resolved the issue by the solution you mentioned above.

**Comment by mdiflorio** [comment]
@bindmisson Post how you fixed the issue.

@americandy Did you happen to find a solution?

**Comment by sufyanaslam** [comment]
@mierz00 @americandy already posted the solution. It helped me to solve the issue. 

I set the cocorico_core.assets_base_ulrs to the Server IP, so it looks like:
cocorico_core.assets_base_urls: 'http://134.209.249.25'

**Comment by mdiflorio** [comment]
Thanks for the response @sufyanaslam. 

It's a little bit strange, it seems to work on and off on my AWS server.

**Comment by ghost** [comment]
Hello, I am trying to run cocorico with docker on aws with ubuntu 18.04
Apparently all works fine with the exception of boostrap, which send this error message:
PHP Warning:  Version warning: Imagick was compiled against Image Magick version 1799 but version 1800 is loaded. Imagick will run but may behave surprisingly in Unknown on line 0

I already changed, as suggested, the cocorico_core.assets_base_urls value on the app/config/parameters.yml file, but it still shows as an error. Any idea on how to fix this?

Thank you very much!

**Comment by crocodeal45** [comment]
Hi
Im trying to run cocorico with docker too. Im on Debian 9 on VPS and  now im on the same page with " File not found " on front. Im student i need to learn Cocorico  so if someone know how to use cocorico please contacte me i can pay for lecon thanks you

**Comment by elhayadi** [comment]
Just run this command in your poject directory
php composer.phar install
and refresh your wamp
