### ISSUE TITLE
Favourites Tab not working with docker setup

### ISSUE THREAD

**Issue by mecjack** [Cocolabs-SAS/cocorico-docker#3]
Why is the "Favorites" tab not working with the docker setup, but in your online demo its working?
Is the GitHub code different to your online demo code?

I get the following exception:

Variable "form" does not exist in @CocoricoCore/Frontend/ListingResult/result.html.twig at line 55

**Comment by giorgio654** [comment]
Hello @mecjack,
A PR will be merged soon to fix this issue. [#138](https://github.com/Cocolabs-SAS/cocorico/pull/138)

**Comment by cocolabssas** [comment]
Hi,

The PR is merged :)
