### ISSUE TITLE
Allow start of cocorico without volumes.

### ISSUE THREAD

**Issue by rhuanbarreto** [Cocolabs-SAS/cocorico-docker#6]
I wanted to run cocorico only for evaluating and I couldn't run this without the use of the volumes.

The volumes creates unecessary files outside the container, once a container is ephemeral by definition.

You could use mkdir -p /data/db on the script so mongo could run normally without decalring the volume.

**Comment by giorgio654** [comment]
Hello @rhuanbarreto,
A new release will be published in the next days. https://github.com/Cocolabs-SAS/cocorico-docker/pull/11
