### ISSUE TITLE
docker installation issue

### ISSUE THREAD

**Issue by chrigui** [Cocolabs-SAS/cocorico-docker#7]
hello,
is this normal for a fresh VPS: http://104.248.40.159/en/
its 1 GB Digitalocean vps
many thanks.

**Comment by eogunjirin** [comment]
hey @chrigui did you get that error fixed its the same issue i have

**Comment by giorgio654** [comment]
Hello @chrigui, @EmmaTheGr8est,
A new release will be published in the next days. https://github.com/Cocolabs-SAS/cocorico-docker/pull/11
