### ISSUE TITLE
Base de donnée vide

### ISSUE THREAD

**Issue by Nanou2206** [Cocolabs-SAS/cocorico-docker#7]
Bonjour

Je viens d'installer cocorico avec docker et j'ai un message d'erreur 
An exception occurred while executing 'SELECT DISTINCT id_1 FROM (SELECT '' AS sclr_0, l0_.id AS id_1, l0_.price AS price_2, l0_.certified AS certified_3, l0_.average_rating AS average_rating_4, l0 etc...

La Base de données cocorico_dev ne contient aucune table.
Est ce normal ?

Merci de votre aide

**Comment by giorgio654** [comment]
Hi @Nanou2206,
You have to follow the installation instruction : https://github.com/Cocolabs-SAS/cocorico/blob/master/doc/installation.md
