### ISSUE TITLE
Questions about how it works 

### ISSUE THREAD

**Issue by FredSWR** [Cocolabs-SAS/cocorico-docker#8]
Hi !

We use cocorico for a school project and we have some questions about how it works.

We installed cocorico with docker and everything went well but we are technically limited. Can you help us by answering these questions :
- How to access the Mongodb database ?
- Is there a configuration for sending mail ? Forgotten password for example.
- Can we connect COCORICO to a mobile application via a webservice or other means ? 

Your help would be very precious for us. 

Thanks !

**Comment by giorgio654** [comment]
Hello @FredSWR,

You can use a MongoDB client like [Robo 3T](https://robomongo.org/download) with the basic parameters:

- Address: 127.0.0.1
- Port: 27017
- Database: cocorico

You can use a Gmail account to send emails for example.
Documentation is here: https://symfony.com/doc/2.8/email/gmail.html

Cocorico didn't provide API yet, but stay tuned. :+1:
